services:
  # Backend API (Express.js)
  - type: web
    name: meal-creator-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: SECRET
        generateValue: true

  # Frontend (Next.js)
  - type: web
    name: meal-creator-frontend
    env: node
    buildCommand: cd "REACT PROJECT" && npm install && npm run build
    startCommand: cd "REACT PROJECT" && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://meal-creator-api.onrender.com

